#!/bin/sh /etc/rc.common
#-- Copyright (C) 2018 dz <dingzhong110@gmail.com>

START=98

re=0

start(){
	enable=$(uci get bbr.config.enabled)
	if [ $enable -eq 1 ]; then
		echo "enable"
		lsmod | grep bbr
		if [ "$?" == "0" ]; then
			echo "The BBR module has been loaded."
		else
			insmod tcp_bbr
			sleep 3
		fi
		echo "tcp_bbr" > /etc/modules.d/bbr
		sed -i '/bbr/d' /etc/sysctl.conf
		echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
		echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
		sysctl -p
	fi
}

stop(){
    enable=$(uci get bbr.config.enabled)	
    if [ $enable -ne 1 ]; then
	echo "disable"
	rmmod tcp_bbr
	echo "net.ipv4.tcp_congestion_control=cubic" >> /etc/sysctl.conf
	sed -i '/bbr/d' /etc/sysctl.conf
	sed -i '/net.core.default_qdisc/d' /etc/sysctl.conf
	sysctl -p
	sleep 1
	sed -i '/net.ipv4.tcp_congestion_control/d' /etc/sysctl.conf
	sysctl -p
	fi
}

restart(){
	stop
	start
}