#!/bin/sh /etc/rc.common
#-- Copyright (C) 2018 dz <dingzhong110@gmail.com>

START=99

re=0

CRON_FILE=/etc/crontabs/root

start(){
	echo "enable"
	enable=$(uci get fullconenat.config.enabled 2>/dev/null)
	all_enable=$(uci get fullconenat.config.all_enabled 2>/dev/null)
	fullconenat_ip=$(uci get fullconenat.config.fullconenat_ip 2>/dev/null)
	if [ $enable -eq 1 ]; then
	iptables -t nat -D zone_wan_prerouting -j FULLCONENAT
	iptables -t nat -D zone_wan_postrouting -s $fullconenat_ip -j FULLCONENAT
	iptables -t nat -D zone_wan_postrouting -j MASQUERADE
	iptables -t nat -D zone_wan_postrouting -j FULLCONENAT
	sleep 3
	insmod xt_FULLCONENAT
	sleep 3
	sed -i '/FULLCONENAT/d' /etc/firewall.user
	sed -i '/zone_wan_postrouting -j MASQUERADE/d' /etc/firewall.user
		if [ $all_enable -eq 0 ]; then
			echo "iptables -t nat -A zone_wan_prerouting -j FULLCONENAT" >> /etc/firewall.user
			echo "iptables -t nat -A zone_wan_postrouting -s $fullconenat_ip -j FULLCONENAT" >> /etc/firewall.user
			echo "iptables -t nat -A zone_wan_postrouting -j MASQUERADE" >> /etc/firewall.user
		elif [ $all_enable -eq 1 ]; then
			echo "iptables -t nat -A zone_wan_prerouting -j FULLCONENAT" >> /etc/firewall.user
			echo "iptables -t nat -A zone_wan_postrouting -j FULLCONENAT" >> /etc/firewall.user
		fi
		sleep 1
		uci set firewall.@zone[1].masq=0
		uci commit firewall
			if [ $re -eq 0 ]; then
				echo $re
				/etc/init.d/firewall restart
			fi 
	add_cron
	wan_ip=$(ubus call network.interface.wan status | grep "address" | grep -oE '[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}')
	sed -i '1,3d' /etc/fullconenat/fullconenat-ip1
	echo "$wan_ip" >> /etc/fullconenat/fullconenat-ip1
	fi
}

stop(){
	echo "stop"
	fullconenat_ip=$(uci get fullconenat.config.fullconenat_ip 2>/dev/null)
    enable=$(uci get fullconenat.config.enabled 2>/dev/null)	
    if [ $enable -eq 0 ]; then
		echo "disable"
		rmmod xt_FULLCONENAT
		sleep 1
		iptables -t nat -D zone_wan_prerouting -j FULLCONENAT
		iptables -t nat -D zone_wan_postrouting -s $fullconenat_ip -j FULLCONENAT
		iptables -t nat -D zone_wan_postrouting -j MASQUERADE
		iptables -t nat -D zone_wan_postrouting -j FULLCONENAT
		sed -i '/zone_wan_postrouting -j MASQUERADE/d' /etc/firewall.user
		sed -i '/FULLCONENAT/d' /etc/firewall.user
		uci set firewall.@zone[1].masq=1
		uci commit firewall
	    if [ $re -ne 1 ]; then
			echo $re
			/etc/init.d/firewall restart
        fi 
	del_cron
	fi
}


restart(){
	re=1
	stop
	start
	/etc/init.d/firewall restart
}

add_cron()
{
	sed -i '/fullconenat_watchdog.log/d' $CRON_FILE
	echo '*/5 * * * * /etc/fullconenat/fullconenat-watchdog >> /tmp/fullconenat_watchdog.log 2>&1' >> $CRON_FILE
	crontab $CRON_FILE
}

del_cron()
{
	sed -i '/fullconenat_watchdog.log/d' $CRON_FILE
	/etc/init.d/cron restart
}
