#!/bin/sh /etc/rc.common
#-- Copyright (C) 2018 dz <dingzhong110@gmail.com>

START=99

start(){
	enable=$(uci get bbr.config.enabled)
	bbr_mod_enable=$(uci get bbr.config.bbr_mod_enabled)
	if [ $enable -eq 1 ]; then
		echo "enable"
		if [ $bbr_mod_enable -eq 0 ]; then
			insmod bbr
			sleep 3
			echo "bbr" > /etc/modules.d/bbr
			sed -i '/bbr/d' /etc/sysctl.conf
			echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
		elif [ $bbr_mod_enable -eq 1 ]; then
			rmmod bbr
			insmod tcp_bbr_mod
			sleep 3
			echo "tcp_bbr_mod" > /etc/modules.d/bbr
			sed -i '/bbr/d' /etc/firewall.user
			echo "net.ipv4.tcp_congestion_control=tcp_bbr_mod" >> /etc/sysctl.conf
		fi
		sysctl -p
	fi
}

stop(){
    enable=$(uci get bbr.config.enabled)	
    if [ $enable -ne 1 ]; then
		echo "disable"
		rmmod bbr
		rmmod tcp_bbr_mod
		echo "net.ipv4.tcp_congestion_control=cubic" >> /etc/sysctl.conf
		sed -i '/bbr/d' /etc/sysctl.conf
		sysctl -p
		sleep 1
		sed -i '/cubic/d' /etc/sysctl.conf
		sysctl -p
	fi
}

restart(){
	stop
	start
}