#-- Copyright (C) 2018 dz <dingzhong110@gmail.com>

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for FullConeNat
LUCI_DEPENDS:=+kmod-ipt-fullconenat
LUCI_PKGARCH:=all
PKG_VERSION:=1.2
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

